namespace: minio

stack:
  defines: process-group
  runnable-list:
    - minio/minio1
    - minio/minio2
    - minio/nginx
  variables:
    monk_minio_port:
      env: MINIO_PORT
      type: int
      value: 9000
    monk_console_port:
      env: MINIO_CONSOLE_PORT
      type: int
      value: 9001
    monk_minio_admin_password:
      value: password
    monk_minio_admin_username:
      value: admin
    server_name:
      value: minio.monk.io
    listen_port:
      value: 81
    listen_api_port:
      value: 80